site_name: ROS2 by Projects
repo_url: https://github.com/roboclubdtu/ros2-prj
site_description: Learning ROS2 through projects
site_author: Meltwin
copyright: © 2024 - DTU Roboclub
docs_dir: docs
site_dir: build
nav:
  - Home: index.md
extra_css:
  - assets/custom_css.css
theme:
  name: material
  favicon: assets/Logo_Thicker.svg
  logo: assets/Logo_Thicker.svg
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
      primary: black
      accent: red

    # Palette toggle for dark mode
    - scheme: slate
      logo: assets/Logo_WR.svg
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
      primary: red
      accent: cyan
  features:
    - content.code.copy
    - content.code.select
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html
  - footnotes
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - admonition
  - pymdownx.details